version: '3.6'
networks:
  kafka-example-network:
     ipam:
      config:
        - subnet: 172.80.0.0/24

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
     - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=ocsen_zookeeper
      - ZOO_SERVER_PASSWORDS=ocsen_zookeeper_password
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    networks:
      kafka-example-network:
        ipv4_address: 172.80.0.2

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://172.80.0.3:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://172.80.0.3:9092
      - KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      
      - KAFKA_CFG_ZOOKEEPER_CONNECT=172.80.0.2:2181
      - KAFKA_ZOOKEEPER_USER=ocsen_zookeeper
      - KAFKA_ZOOKEEPER_PASSWORD=ocsen_zookeeper_password

      - KAFKA_INTER_BROKER_USER=ocsen_inter
      - KAFKA_INTER_BROKER_PASSWORD=ocsen_inter_password
      
      - KAFKA_BROKER_USER=ocsen_broker
      - KAFKA_BROKER_PASSWORD=ocsen_broker_password
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      kafka-example-network:
        ipv4_address: 172.80.0.3

  # producer:
  #   image: 'ocsen-service:latest'
  #   volumes:
  #     - ./producer:/app
  #   ports:
  #     - '8080:8080'
  #   networks:
  #     kafka-example-network:
  #       ipv4_address: 172.80.0.4

  # consumer:
  #   image: 'ocsen-service:latest'
  #   volumes:
  #     - ./consumer:/app
  #   ports:
  #     - '8081:8081'
  #   networks:
  #     kafka-example-network:
  #       ipv4_address: 172.80.0.5

volumes:
  zookeeper-data:
    driver: local
  kafka-data:
    driver: local
